after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:

install:
  - bundle install --without development
language: ruby
notifications:
  email:
    recipients:
      - alison.rowland@gsa.gov
      - amos.stone@businessusa.gov
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake test
services: mysql
rvm:
  - 2.0.0
  - 1.9.3
branches:
  only:
    - master