Registrations:
  "SAM (System of Award Management) Registration Process":
    description: "The System for Award Management (SAM) is the Official U.S. Government system that consolidated the capabilities of CCR/FedReg, ORCA, and EPLS. This is your starting point for clearing the requirements of RFP-EZ and various other platforms within the federal government. Often, this process can seem daunting and you might not know where to start. Our walkthrough allows you to collect the necessary information you will need to complete SAM registration ahead of time. Furthermore, business owners can get the help they need at any step along the SAM path."
    link:
      name: Registration Start URL
      url: "https://www.sam.gov/portal/public/SAM/"
    children:
      "Registration Overview":
        dependencies: "Requires a user account on SAM.gov from: https://www.sam.gov/portal/public/SAM/"
        link:
          name: SAM User Account Registration
          url: "https://www.sam.gov/portal/public/SAM/"
        tag_list: external dependency
      "CreateAnAccountChooseAnAccountType":
        "descripton":
            "There are two types of SAM accounts.  To register your business, you will need an Individual Account.  Choose 'Create an Account' to get started."
      "PersonalInformation":
        "descripton": "This page allows you to create the basic information needed to create your individual user account."
      "formData":
        "fields:
            [
                {
                "matchString": "Title",
                "required": "false",
                "valid": "Any pull-down value",
                "hover": "Your address title",
                "focus": "Choose a value",
                "unfocused": "Oops, your title is invalid",
                "validator": {
                    "type": "none",
                    "rules": null
                }
                },
                {
                "matchString": "First Name",
                "required": "true",
                "hover": "Your legal first or given name",
                "valid": "alphabetic characters only\n14 character maximum",
                "focus": "Enter your name",
                "unfocused": "don't you know your own name?",
                "validator": {
                    "type": "alpha-string",
                    "rules": {
                    "type": "alpha-string",
                    "length": "14"
                    }
                }
                },
                {
                "matchString": "Middle Initial",
                "required": "false",
                "valid": "one letter only, no punctuation",
                "hover": "Your middle initial",
                "focus": "enter your initial",
                "unfocused": "one letter only please",
                "validator": {
                    "type": "none",
                    "rules": null
                }
                },
                {
                "matchString": "Last Name",
                "required": "true",
                "hover": "Your legal last or family name",
                "valid": "alphabetic characters only\n14 character maximum",
                "focus": "please enter your family name",
                "unfocused": "Oops, your name is invalid",
                "validator": {
                    "type": "alpha-string",
                    "rules": {
                    "type": "alpha-string",
                    "length": "14"
                    }
                }
                },
                {
                "matchString": "Suffix",
                "required": "false",
                "valid": "any characters",
                "hover": "Suffix",
                "focus": "Enter a suffix if desired",
                "unfocused": "",
                "validator": {
                    "type": "none",
                    "rules": null
                }
                },
                {
                "matchString": "Email Address",
                "required": "true",
                "valid": "must be a legal email address",
                "hover": "Primary contact email address",
                "focus": "please enter your email address",
                "unfocused": "this is not a valid email",
                "validator": {
                    "type": "email"
                }
                },
                {
                "matchString": "Confirm Email Address",
                "required": "true",
                "valid": "must match email address",
                "hover": "Confirm your contact email address",
                "focus": "Please confirm your email address",
                "unfocused": "this is not a match",
                "validator": {
                    "type": "confirm",
                    "rules": {
                        "type": "confirm",
                    "matchField": "Email Address"
                    }
                }
                },
                {
                "matchString": "Phone",
                "required": "true",
                "hover": "Your primary phone number",
                "valid": "10 digit us phone number",
                "focus": "Enter your phone number",
                "unfocused": "Oops, your name is invalid",
                "validator": {
                    "type": "us-phone",
                    "rules": {
                    "type": "us-phone"
                    }
                }
                },
                {
                "matchString": "Phone Extension",
                "required": "false",
                "hover": "extension",
                "valid": "anything",
                "focus": "Enter any necessary extension",
                "unfocused": "",
                "validator": {
                    "type": "none",
                    "rules": null
                }
                },
                {
                "matchString": "Fax",
                "required": "false",
                "hover": "Fax number",
                "valid": "10 digit us phone number",
                "focus": "Enter your fax number",
                "unfocused": "",
                "validator": {
                    "type": "us-phone",
                    "rules": {
                    "type": "us-phone"
                    }
                }
                }
            ]
      "Purpose of Registration":
        children:
          "Determine Purpose":
          "Core Data":
            dependencies: "Requires a valid 9-digit DUNS number from http://fedgov.dnb.com/webform/displayHomePage.do"
            link:
              name: "Get a DUNS Number"
              url: "http://fedgov.dnb.com/webform/displayHomePage.do"
          "Business Information":
          "IRS Consent":
            dependencies: "Your company's Tax Identification Number (TIN)"
            link:
              name: "Get a Tax Identification Number (TIN)"
              url: "http://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Apply-for-an-Employer-Identification-Number-(EIN)-Online"
          "CAGE or NCAGE Code":
            dependencies: "CAGE Code: You need to bring it if you have it, or SAM will automatically assign you one'"
          "General Information":
          "Financial Information":
            dependencies: "EFT: Account Type, Routing Number, Account Number, ACH US Phone, ACH Non-US Phone, ACH Fax, ACH Email"
          "Executive Compensation Questions":
          "Proceedings Questions":
          "Information Opt-Out":
      "Assertions":
        children:
          "Goods and Services (NAICS, PSC)":
            dependencies: "NAICS Code (industry classification)-- SAM will provide a search but users could also pre-locate their code via the Census search tool: http://www.census.gov/eos/www/naics/. Product or Service Codes"
            link:
              name: "Census Search Tool"
              url: "http://www.census.gov/eos/www/naics/"
          "Size Metrics":
          "EDI Information":
          "Disaster Relief Information":
      "Representation and Certifications":
        children:
          "FAR Response 1 (Federal Acquisition Regulation)":
          "FAR Response 2":
          "FAR Response 3":
          "FAR Response 4":
          "Architect-Engineer Response":
          "Defense Response":
      "Points of Contact":
        children:
          "Points of Contact Details":
      "Small Business Certification":
        children:
          "Small Business Association Profile":
